name: Train Model with MLflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env

      - name: Install MLflow
        run: |
          pip install mlflow==2.19.0

      - name: Run training with MLflow
        shell: bash -l {0}
        run: |
          mlflow run MLProject \
            -P n_estimators=150 \
            -P max_depth=12 \
            -P min_samples_split=3 \
            -P min_samples_leaf=2

      - name: Commit and push to master
        run: |
          git config --global user.name "${{ secrets.username }}"
          git config --global user.email "${{ secrets.email }}"

          git remote set-url origin https://${{ secrets.token }}@github.com/${{ github.repository }}

          # Buat branch master jika belum ada
          git fetch origin
          if ! git show-ref --quiet refs/remotes/origin/master; then
            git checkout --orphan master
            git rm -rf .
            git commit --allow-empty -m "Initial commit on master"
            git push origin master
          fi

          # Checkout ke branch master dan merge dari main (optional)
          git checkout master
          git merge main --no-edit || echo "Nothing to merge from main"

          # Tambahkan dan commit folder mlruns
          git add mlruns/
          git commit -m "Add or update mlruns from CI" || echo "No changes to commit"
          git push origin master