name: Train Model with MLflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env

      - name: Install MLflow
        run: |
          pip install mlflow==2.19.0

      - name: Run training with MLflow
        shell: bash -l {0}
        run: |
          mlflow run MLProject --n_estimators 150 --max_depth 12 --min_samples_split 3 --min_samples_leaf 2

      - name: Commit and push to master
        run: |
          git config --global user.name "${{ secrets.username }}"
          git config --global user.email "${{ secrets.email }}"
          git fetch origin master
          git checkout master
          git merge main --no-edit
          git add mlruns/
          git commit -m "Merge log from main and add mlruns" || echo "No changes to commit"
          git push origin master